Add labels
operate-first/alertmanager-github-receiver pull request #1
Opened 2021-09-30 15:40 UTC by Gregory-Pereira

I am struggling a bit with the processAlerts test in handler.go, so hoping that I can get some help with that.

2021-09-30 15:40 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Falertmanager-github-receiver).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/alertmanager-github-receiver/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-11-05 17:09 UTC, Gregory-Pereira commented
@HumairAK please help

2021-11-24 00:25 UTC, Gregory-Pereira commented
Go does not support function with variable-length arrays, must find a way to initialized the function with structured string array size for the NewReciever funciton

2021-12-06 18:43 UTC, Gregory-Pereira commented
/cc @HumairAK

2021-12-08 18:40 UTC, HumairAK requested changes

2021-12-08 18:40 UTC, HumairAK commented on alerts/template_test.go
> +func containsArray(arr []string, str string) (bool) {
This doesn't look like it's used anywhere

2021-12-08 18:40 UTC, HumairAK commented on alerts/template_test.go
> +					Labels: amtmpl.KV{"cluster": "rick", "namespace": "opf-ci-pipelines"},
can you switch these to use none operate-first related labels? anything generic works (same as above)

2021-12-08 18:40 UTC, HumairAK commented on alerts/template_test.go
> +					Labels: amtmpl.KV{"cluster": "smaug", "namespace": "openshift-monitoring"},
can you switch these to use none operate-first related labels? anything generic works (same as above)

2021-12-08 18:40 UTC, HumairAK commented on alerts/template_test.go
> +					Labels: amtmpl.KV{"cluster": "rick", "namespace": "opf-ci-pipelines"},
can you switch these to use none operate-first related labels? anything generic works, like: 
```
Labels: amtmpl.KV{"testkey1": "testval1", "testkey2": "testval2"},
```

2021-12-08 18:40 UTC, HumairAK commented on alerts/template_test.go
> +					Labels: amtmpl.KV{"cluster": "smaug", "namespace": "openshift-monitoring"},
can you switch these to use none operate-first related labels? anything generic works (same as above)

2021-12-08 18:40 UTC, HumairAK commented on alerts/template_test.go
> +	var expectOutputTest6 = make([]string, 0)
I would get rid of these assignments and include them directly in the struct creations, e.g.: 

 ```
 {
	testName: "test status directly", 
	labelsTmpl: "{{.Status}}", 
	expectErrTxt: "", 
	expectOutput: []string{"firing"},   // get rid of expectOutputTest3 entirely
}
 ```

2021-12-08 18:40 UTC, HumairAK commented on alerts/template_test.go
> +	var expectOutputTest6 = make([]string, 0)
also once again make these outputs generic, prod/stage is fine, but `openshift-monitoring/rick/opf-ci-pipelines/etc` are operate-first specific.

2021-12-08 18:40 UTC, HumairAK commented on alerts/template_test.go
> +			fmt.Println("labels: ", labels)
don't need print statements

2021-12-08 18:40 UTC, HumairAK commented on alerts/template_test.go
> +		fmt.Println(testName)
don't need print statements

2021-12-08 18:40 UTC, HumairAK commented on alerts/template_test.go
> +		fmt.Println(testName)
don't need print statements

2021-12-08 18:40 UTC, HumairAK commented on alerts/template_test.go
> +			fmt.Println("title: ", title)
don't need print statements

2021-12-08 18:40 UTC, HumairAK commented on README.md
> +## Additional Configuration for Github Spefic Labels
I would change 

> Additional Configuration for Github Spefic Labels 

To

> Additional Configuration for Converting alert labels to GitHub labels

2021-12-08 18:40 UTC, HumairAK commented on README.md
> +In adition to mounting the labelmap configuration file, make sure to add the -label-template-file flag as a parameter to the Dockerfile as it is currently.
This isn't specific to dockerfile but the app itself, just say something like: 

> To add the label map file mentioned [here](link to above) just you can use the `-label-template-file`. For example: 
```
$alertmanager-github-receiver -authtoken=${token} -org=${org} -repo=${repo} -label-template-file=${path-to-labelmap}
```

2022-03-11 01:09 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2022-04-10 02:28 UTC, sesheta commented
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

2022-04-11 15:03 UTC, Gregory-Pereira commented
/lifecycle frozen

2022-04-11 15:03 UTC, sesheta commented
@Gregory-Pereira: The `lifecycle/frozen` label cannot be applied to Pull Requests.

<details>

In response to [this](https://github.com/operate-first/alertmanager-github-receiver/pull/1#issuecomment-1095166709):

>/lifecycle frozen


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-04-11 15:08 UTC, HumairAK commented
/remove-lifecycle rotten

2022-07-10 16:03 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2022-08-09 18:54 UTC, sesheta commented
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

2022-08-30 06:26 UTC, durandom commented
@Gregory-Pereira is this basically working? If so, I suggest to open a PR already to upstream and get some feedback there.
This is great work and should be exposed 👏

2022-09-03 22:24 UTC, Gregory-Pereira commented
excellent idea @durandom. Going to re-review myself and breathe some life into it, before submitting it as an upstream contribution.
/remove lifecycle/rotten

2022-09-03 22:25 UTC, Gregory-Pereira commented
/remove-lifecycle rotten

2022-09-03 22:25 UTC, Gregory-Pereira commented
bump @Gregory-Pereira

2022-12-05 17:25 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2023-01-04 17:29 UTC, sesheta commented
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

2023-02-03 18:16 UTC, sesheta commented
Rotten issues close after 30d of inactivity.
Reopen the issue with `/reopen`.
Mark the issue as fresh with `/remove-lifecycle rotten`.

/close

2023-02-03 18:16 UTC, closed without merging

2023-02-03 18:16 UTC, sesheta commented
@sesheta: Closed this PR.

<details>

In response to [this](https://github.com/operate-first/alertmanager-github-receiver/pull/1#issuecomment-1416232628):

>Rotten issues close after 30d of inactivity.
>Reopen the issue with `/reopen`.
>Mark the issue as fresh with `/remove-lifecycle rotten`.
>
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>